#! /bin/sh

sxhkd &
feh --bg-fill '/home/jonathan/.local/share/wp/wallpaper.png'

killall -q polybar
polybar example &

bspc monitor -d I II III IV

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      true
